### ISSUE TITLE
Feature Request: Support :focus-within

### ISSUE THREAD

**Issue by AverageMarcus** [SamsungInternet/support#18]
The `:focus-within` pseudo class makes it easier to build accessible slide-out/reveal navigation without the need for JavaScript. 

Current support is really good: [Can I Use...](http://caniuse.com/#feat=css-focus-within)

**Resources:**
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within)
[Specification Draft](https://drafts.csswg.org/selectors-4/#the-focus-within-pseudo)
[Edge User Voice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/11725071-implement-focus-within-from-selectors-4)

**Example:**
[JS Bin](http://jsbin.com/qadigoc/3/edit?html,css,output)
```css
menu .menu-toggle:focus + .menu-list,
menu .menu-list:focus-within {
  transform: translateX(0);
}

menu .menu-list {
  position: fixed;
  left: 0;
  transform: translateX(-100%);
  transition: all 0.5s;
}
```
```html
<menu>
  <a href="#" class="menu-toggle">Menu</a>
  <ul class="menu-list">
    <li><a href="/">home</a></li>
    <li><a href="/about">about</a></li>
    <li><a href="/contact">contact us</a></li>
  </ul>
</menu>
```

Incompatibility of browsers means the pseudo class must be included as a separate CSS rule:
```css
menu .menu-toggle:focus + .menu-list {
  transform: translateX(0);
}

menu .menu-list:focus-within {
  transform: translateX(0);
}
```
